# Generated by Django 2.1.7 on 2019-03-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemdetails',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemdetails',
            name='price',
        ),
    ]
