# Generated by Django 2.1.7 on 2019-03-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0002_auto_20190326_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='coordinates',
            field=models.CharField(default='', max_length=500),
        ),
    ]
