# Generated by Django 2.1.7 on 2019-03-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0005_auto_20190328_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styles',
            name='roomId',
        ),
        migrations.AddField(
            model_name='document',
            name='style1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='style2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Styles',
        ),
    ]
