# Generated by Django 2.2 on 2019-04-23 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0007_auto_20190328_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
