# Generated by Django 2.2 on 2019-05-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0008_auto_20190423_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='breadth',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='length',
            field=models.TextField(default=0),
        ),
    ]
