# Generated by Django 2.2 on 2019-05-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0009_auto_20190528_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ibreadth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='ilength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='breadth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
